export const designTokens = {
  colors: {
    primary: {
      DEFAULT: "hsl(var(--primary))",
      foreground: "hsl(var(--primary-foreground))",
    },
    secondary: {
      DEFAULT: "hsl(var(--secondary))",
      foreground: "hsl(var(--secondary-foreground))",
    },
    accent: {
      DEFAULT: "hsl(var(--accent))",
      foreground: "hsl(var(--accent-foreground))",
    },
    success: {
      DEFAULT: "hsl(var(--success))",
      foreground: "hsl(var(--success-foreground))",
    },
    warning: {
      DEFAULT: "hsl(var(--warning))",
      foreground: "hsl(var(--warning-foreground))",
    },
    error: {
      DEFAULT: "hsl(var(--error))",
      foreground: "hsl(var(--error-foreground))",
    },
    background: "hsl(var(--background))",
    foreground: "hsl(var(--foreground))",
    muted: "hsl(var(--muted))",
    mutedForeground: "hsl(var(--muted-foreground))",
    border: "hsl(var(--border))",
    glass: "hsla(var(--glass))",
    overlay: "hsla(var(--overlay))",
  },
  gradients: {
    hero: "var(--gradient-hero)",
    aurora: "var(--gradient-aurora)",
    mesh: "var(--gradient-mesh)",
    soft: "var(--gradient-soft)",
  },
  shadows: {
    soft: "var(--shadow-soft)",
    medium: "var(--shadow-medium)",
    strong: "var(--shadow-strong)",
    glass: "var(--shadow-glass)",
    glow: "var(--shadow-glow)",
  },
  radii: {
    xs: "var(--radius-xs)",
    sm: "var(--radius-sm)",
    md: "var(--radius-md)",
    lg: "var(--radius-lg)",
    xl: "var(--radius-xl)",
    "2xl": "var(--radius-2xl)",
    "3xl": "var(--radius-3xl)",
    pill: "9999px",
  },
  opacity: {
    4: 0.04,
    8: 0.08,
    12: 0.12,
    16: 0.16,
    24: 0.24,
    32: 0.32,
    48: 0.48,
    64: 0.64,
    80: 0.8,
    96: 0.96,
  },
  blur: {
    xs: "4px",
    sm: "8px",
    md: "12px",
    lg: "20px",
    xl: "28px",
    "2xl": "40px",
    "3xl": "64px",
  },
  spacing: {
    xs: "0.25rem",
    sm: "0.5rem",
    md: "0.75rem",
    lg: "1rem",
    xl: "1.5rem",
    "2xl": "2rem",
    "3xl": "3rem",
    "4xl": "4rem",
    "5xl": "6rem",
    "6xl": "8rem",
  },
  typography: {
    display: "3.75rem",
    h1: "3rem",
    h2: "2.25rem",
    h3: "1.875rem",
    h4: "1.5rem",
    body: "1rem",
    caption: "0.875rem",
    label: "0.8125rem",
    mono: "0.875rem",
  },
  motion: {
    durations: {
      fastest: 120,
      fast: 180,
      normal: 240,
      slow: 320,
      slower: 480,
      cinematic: 700,
    },
    easings: {
      standard: [0.2, 0.8, 0.2, 1],
      expressive: [0.16, 1, 0.3, 1],
      crisp: [0.4, 0, 0.2, 1],
      soft: [0.25, 0.1, 0.25, 1],
    },
  },
  zIndex: {
    base: 0,
    sticky: 20,
    header: 30,
    overlay: 40,
    modal: 50,
    popover: 60,
    toast: 70,
    debug: 999,
  },
} as const;

export type DesignTokens = typeof designTokens;
